server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    driverClassName: com.mysql.cj.jdbc.Driver
    password: TaiMar198
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: "org.hibernate.dialect.MySQLDialect"

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 25 # in second
  refreshable-duration: 2500 # in seconds
